insert into tb_country(country, alpha)
values('France','fr'),
('Turkey','tr'),
('South Africa','za'),
('Bulgaria','bg'),
('Russia','ru'),
('Peru','pe'),
('Bolivia','bo'),
('Scotland','sco'),
('Croatia','hr'),
('Venezuela','ve'),
('Belgium','be'),
('Austria','at'),
('Chile','cl'),
('Colombia','co'),
('Serbia','rs'),
('Ecuador','ec'),
('Czech Republic','cz'),
('Denmark','dk'),
('Brazil','br'),
('Saudi Arabia','sa'),
('Romania','ro'),
('Germany','de'),
('Netherlands','nl'),
('Switzerland','ch'),
('England','eng'),
('Australia','au'),
('Norway','no'),
('Portugal','pt'),
('Hungary','hu'),
('Poland','pl'),
('Paraguay','py'),
('Italy','it'),
('Spain','es'),
('Ukraine','ua'),
('Greece','gr'),
('Uruguay','uy'),
('Iran','ir');