drop procedure if exists p_insert_squad;
create procedure p_insert_squad(
  _date date,
  _squad_id varchar(50),
  _attendance numeric(7,1),
  _captain varchar(50),
  _competition varchar(75),
  _dayofweek varchar(3),
  _formation varchar(15),
  _goals_against numeric(3,1),
  _goals_for numeric(3,1),
  _governing_country varchar(50),
  _opponent varchar(50),
  _possession numeric(7,1),
  _referee varchar(70),
  _result char(1),
  _round varchar(60),
  _squad varchar(75),
  _venue varchar(8),
  _average_shot_distance numeric(7,1),
  _goals numeric(3,1),
  _goals_per_shot numeric(3,2),
  _goals_per_shot_on_target numeric(3,2),
  _pens_att numeric(3,1),
  _pens_made numeric(3,1),
  _shots_on_target numeric(3,1),
  _shots_on_target_pct numeric(7,1),
  _shots_total numeric(3,1),
  _opponent_goals numeric(3,1),
  _opponent_goals_against numeric(3,1),
  _opponent_goals_for numeric(3,1),
  _opponent_goals_per_shot numeric(3,2),
  _opponent_goals_per_shot_on_target numeric(3,2),
  _opponent_pens_att numeric(3,1),
  _opponent_pens_made numeric(3,1),
  _opponent_shots_on_target numeric(3,1),
  _opponent_shots_on_target_pct numeric(7,1),
  _opponent_shots_total numeric(3,1),
  _clean_sheets numeric(3,1),
  _goals_against_gk numeric(3,1),
  _pens_allowed numeric(3,1),
  _pens_att_gk numeric(3,1),
  _pens_missed_gk numeric(3,1),
  _pens_saved numeric(3,1),
  _save_pct numeric(7,1),
  _saves numeric(3,1),
  _shots_on_target_against numeric(3,1),
  _opponent_clean_sheets numeric(3,1),
  _opponent_goals_against_gk numeric(3,1),
  _opponent_pens_allowed numeric(3,1),
  _opponent_pens_att_gk numeric(3,1),
  _opponent_pens_missed_gk numeric(3,1),
  _opponent_pens_saved numeric(3,1),
  _opponent_save_pct numeric(7,1),
  _opponent_saves numeric(3,1),
  _opponent_shots_on_target_against numeric(3,1),
  _cards_red numeric(3,1),
  _cards_yellow numeric(3,1),
  _cards_yellow_red numeric(3,1),
  _crosses numeric(3,1),
  _fouled numeric(3,1),
  _fouls numeric(3,1),
  _interceptions numeric(3,1),
  _offsides numeric(3,1),
  _own_goals numeric(3,1),
  _pens_conceded numeric(3,1),
  _pens_won numeric(3,1),
  _tackles_won numeric(3,1),
  _opponent_cards_red numeric(3,1),
  _opponent_cards_yellow numeric(3,1),
  _opponent_cards_yellow_red numeric(3,1),
  _opponent_crosses numeric(3,1),
  _opponent_fouled numeric(3,1),
  _opponent_fouls numeric(3,1),
  _opponent_interceptions numeric(3,1),
  _opponent_offsides numeric(3,1),
  _opponent_own_goals numeric(3,1),
  _opponent_pens_conceded numeric(3,1),
  _opponent_pens_won numeric(3,1),
  _opponent_tackles_won numeric(3,1),
  _npxg numeric(7,1),
  _npxg_per_shot numeric(7,1),
  _shots_free_kicks numeric(7,1),
  _xg_net numeric(7,1),
  _avg_distance_def_actions_gk numeric(7,1),
  _crosses_gk numeric(7,1),
  _crosses_stopped_gk numeric(7,1),
  _crosses_stopped_pct_gk numeric(7,1),
  _def_actions_outside_pen_area_gk numeric(7,1),
  _goal_kick_length_avg numeric(7,1),
  _goal_kicks numeric(7,1),
  _passes_completed_launched_gk numeric(7,1),
  _passes_gk numeric(7,1),
  _passes_launched_gk numeric(7,1),
  _passes_length_avg_gk numeric(7,1),
  _passes_pct_launched_gk numeric(7,1),
  _passes_throws_gk numeric(7,1),
  _pct_goal_kicks_launched numeric(7,1),
  _pct_passes_launched_gk numeric(7,1),
  _psxg_gk numeric(7,1),
  _psxg_net_gk numeric(7,1),
  _assisted_shots numeric(7,1),
  _crosses_into_penalty_area numeric(7,1),
  _passes numeric(7,1),
  _passes_completed numeric(7,1),
  _passes_completed_long numeric(7,1),
  _passes_completed_medium numeric(7,1),
  _passes_completed_short numeric(7,1),
  _passes_into_final_third numeric(7,1),
  _passes_into_penalty_area numeric(7,1),
  _passes_long numeric(7,1),
  _passes_medium numeric(7,1),
  _passes_pct numeric(7,1),
  _passes_pct_long numeric(7,1),
  _passes_pct_medium numeric(7,1),
  _passes_pct_short numeric(7,1),
  _passes_progressive_distance numeric(7,1),
  _passes_short numeric(7,1),
  _passes_total_distance numeric(7,1),
  _progressive_passes numeric(7,1),
  _xa numeric(7,1),
  _corner_kicks numeric(7,1),
  _corner_kicks_in numeric(7,1),
  _corner_kicks_out numeric(7,1),
  _corner_kicks_straight numeric(7,1),
  _passes_blocked numeric(7,1),
  _passes_dead numeric(7,1),
  _passes_free_kicks numeric(7,1),
  _passes_ground numeric(7,1),
  _passes_head numeric(7,1),
  _passes_high numeric(7,1),
  _passes_intercepted numeric(7,1),
  _passes_left_foot numeric(7,1),
  _passes_live numeric(7,1),
  _passes_low numeric(7,1),
  _passes_offsides numeric(7,1),
  _passes_oob numeric(7,1),
  _passes_other_body numeric(7,1),
  _passes_pressure numeric(7,1),
  _passes_right_foot numeric(7,1),
  _passes_switches numeric(7,1),
  _through_balls numeric(7,1),
  _throw_ins numeric(7,1),
  _gca numeric(7,1),
  _gca_defense numeric(7,1),
  _gca_dribbles numeric(7,1),
  _gca_fouled numeric(7,1),
  _gca_passes_dead numeric(7,1),
  _gca_passes_live numeric(7,1),
  _gca_shots numeric(7,1),
  _sca numeric(7,1),
  _sca_defense numeric(7,1),
  _sca_dribbles numeric(7,1),
  _sca_fouled numeric(7,1),
  _sca_passes_dead numeric(7,1),
  _sca_passes_live numeric(7,1),
  _sca_shots numeric(7,1),
  _blocked_passes numeric(7,1),
  _blocked_shots numeric(7,1),
  _blocked_shots_saves numeric(7,1),
  _blocks numeric(7,1),
  _clearances numeric(7,1),
  _dribble_tackles numeric(7,1),
  _dribble_tackles_pct numeric(7,1),
  _dribbled_past numeric(7,1),
  _dribbles_vs numeric(7,1),
  _errors numeric(7,1),
  _pressure_regain_pct numeric(7,1),
  _pressure_regains numeric(7,1),
  _pressures numeric(7,1),
  _pressures_att_3rd numeric(7,1),
  _pressures_def_3rd numeric(7,1),
  _pressures_mid_3rd numeric(7,1),
  _tackles numeric(7,1),
  _tackles_att_3rd numeric(7,1),
  _tackles_def_3rd numeric(7,1),
  _tackles_interceptions numeric(7,1),
  _tackles_mid_3rd numeric(7,1),
  _carries numeric(7,1),
  _carries_into_final_third numeric(7,1),
  _carries_into_penalty_area numeric(7,1),
  _carry_distance numeric(7,1),
  _carry_progressive_distance numeric(7,1),
  _dispossessed numeric(7,1),
  _dribbles numeric(7,1),
  _dribbles_completed numeric(7,1),
  _dribbles_completed_pct numeric(7,1),
  _miscontrols numeric(7,1),
  _nutmegs numeric(7,1),
  _pass_targets numeric(7,1),
  _passes_received numeric(7,1),
  _passes_received_pct numeric(7,1),
  _players_dribbled_past numeric(7,1),
  _progressive_carries numeric(7,1),
  _progressive_passes_received numeric(7,1),
  _touches numeric(7,1),
  _touches_att_3rd numeric(7,1),
  _touches_att_pen_area numeric(7,1),
  _touches_def_3rd numeric(7,1),
  _touches_def_pen_area numeric(7,1),
  _touches_live_ball numeric(7,1),
  _touches_mid_3rd numeric(7,1),
  _opponent_possession numeric(7,1),
  _xg_against numeric(7,1),
  _xg_for numeric(7,1)
)
language plpgsql as $$
begin 

  -- Insere os dados do clube
  insert into tb_squad(
    squad_id,
    squad_name,
    competition,
    country
  )
  values(
    _squad_id,
    _squad,
    _competition,
    _governing_country
  )
  on conflict(squad_id)
  do nothing;

  -- Insere infos de rodadas
  insert into tb_squad_round(
    round,
    round_date,
    dayofweek,
    venue,
    squad_id,
    opponent,
    referee,
    result,
    captain,
    formation
  )
  values(
    _round,
    _round_date,
    _dayofweek,
    _venue,
    _squad_id,
    _opponent,
    _referee,
    _result,
    _captain,
    _formation
  )
  on conflict(squad_id, round_date)
  do update
  set round = EXCLUDED.round,
    round_num = EXCLUDED.round_num,
    dayofweek = EXCLUDED.dayofweek,
    venue = EXCLUDED.venue,
    opponent = EXCLUDED.opponent,
    referee = EXCLUDED.referee,
    result = EXCLUDED.result,
    captain = EXCLUDED.captain,
    formation = EXCLUDED.formation
  where squad_id = _squad_id
    and round_date = _round_date
  returning id_squad_round into _id_squad_round;

  -- Insere estatisticas da partida
  insert into tb_squad_match_stats(
    id_squad_round,
    squad_id,
    attendance,
    goals_against,
    goals_for,
    goals_per_shot,
    goals_per_shot_on_target,
    possession,
    average_shot_distance,
    shots_on_target,
    shots_on_target_pct,
    pens_allowed,
    pens_att_gk,
    pens_missed_gk,
    pens_saved,
    pens_att,
    pens_made,
    pens_conceded,
    pens_won,
    shots_total,
    clean_sheets,
    save_pct,
    saves,
    shots_on_target_against,
    cards_red,
    cards_yellow,
    cards_yellow_red,
    crosses,
    fouled,
    fouls,
    interceptions,
    offsides,
    own_goals,
    tackles_won,
    opponent_goals_per_shot,
    opponent_goals_per_shot_on_target,
    opponent_shots_on_target,
    opponent_shots_on_target_pct,
    opponent_shots_total,
    opponent_shots_on_target_against,
    opponent_clean_sheets,
    opponent_pens_att,
    opponent_pens_made,
    opponent_pens_allowed,
    opponent_pens_att_gk,
    opponent_pens_missed_gk,
    opponent_pens_saved,
    opponent_pens_conceded,
    opponent_pens_won,
    opponent_save_pct,
    opponent_saves,
    opponent_cards_red,
    opponent_cards_yellow,
    opponent_cards_yellow_red,
    opponent_crosses,
    opponent_fouled,
    opponent_fouls,
    opponent_interceptions,
    opponent_tackles_won,
    opponent_offsides,
    opponent_own_goals,
    npxg,
    npxg_per_shot,
    shots_free_kicks,
    xg_net,
    avg_distance_def_actions_gk,
    crosses_gk,
    crosses_stopped_gk,
    crosses_stopped_pct_gk,
    def_actions_outside_pen_area_gk,
    goal_kick_length_avg,
    goal_kicks,
    passes_completed_launched_gk,
    passes_gk,
    passes_launched_gk,
    passes_length_avg_gk,
    passes_pct_launched_gk,
    passes_throws_gk,
    pct_goal_kicks_launched,
    pct_passes_launched_gk,
    psxg_gk,
    psxg_net_gk,
    assisted_shots,
    crosses_into_penalty_area,
    passes,
    passes_completed,
    passes_completed_long,
    passes_completed_medium,
    passes_completed_short,
    passes_into_final_third,
    passes_into_penalty_area,
    passes_long,
    passes_medium,
    passes_pct,
    passes_pct_long,
    passes_pct_medium,
    passes_pct_short,
    passes_progressive_distance,
    passes_short,
    passes_total_distance,
    progressive_passes,
    xa,
    corner_kicks,
    corner_kicks_in,
    corner_kicks_out,
    corner_kicks_straight,
    passes_blocked,
    passes_dead,
    passes_free_kicks,
    passes_ground,
    passes_head,
    passes_high,
    passes_intercepted,
    passes_left_foot,
    passes_live,
    passes_low,
    passes_offsides,
    passes_oob,
    passes_other_body,
    passes_pressure,
    passes_right_foot,
    passes_switches,
    through_balls,
    throw_ins,
    gca,
    gca_defense,
    gca_dribbles,
    gca_fouled,
    gca_passes_dead,
    gca_passes_live,
    gca_shots,
    sca,
    sca_defense,
    sca_dribbles,
    sca_fouled,
    sca_passes_dead,
    sca_passes_live,
    sca_shots,
    blocked_passes,
    blocked_shots,
    blocked_shots_saves,
    blocks,
    clearances,
    dribble_tackles,
    dribble_tackles_pct,
    dribbled_past,
    dribbles_vs,
    errors,
    pressure_regain_pct,
    pressure_regains,
    pressures,
    pressures_att_3rd,
    pressures_def_3rd,
    pressures_mid_3rd,
    tackles,
    tackles_att_3rd,
    tackles_def_3rd,
    tackles_interceptions,
    tackles_mid_3rd,
    carries,
    carries_into_final_third,
    carries_into_penalty_area,
    carry_distance,
    carry_progressive_distance,
    dispossessed,
    dribbles,
    dribbles_completed,
    dribbles_completed_pct,
    miscontrols,
    nutmegs,
    pass_targets,
    passes_received,
    passes_received_pct,
    players_dribbled_past,
    progressive_carries,
    progressive_passes_received,
    touches,
    touches_att_3rd,
    touches_att_pen_area,
    touches_def_3rd,
    touches_def_pen_area,
    touches_live_ball,
    touches_mid_3rd,
    opponent_possession,
    xg_against,
    xg_for
  )
  values (
    _id_squad_round,
    _squad_id,
    _attendance,
    _goals_against,
    _goals_for,
    _goals_per_shot,
    _goals_per_shot_on_target,
    _possession,
    _average_shot_distance,
    _shots_on_target,
    _shots_on_target_pct,
    _pens_allowed,
    _pens_att_gk,
    _pens_missed_gk,
    _pens_saved,
    _pens_att,
    _pens_made,
    _pens_conceded,
    _pens_won,
    _shots_total,
    _clean_sheets,
    _save_pct,
    _saves,
    _shots_on_target_against,
    _cards_red,
    _cards_yellow,
    _cards_yellow_red,
    _crosses,
    _fouled,
    _fouls,
    _interceptions,
    _offsides,
    _own_goals,
    _tackles_won,
    _opponent_goals_per_shot,
    _opponent_goals_per_shot_on_target,
    _opponent_shots_on_target,
    _opponent_shots_on_target_pct,
    _opponent_shots_total,
    _opponent_shots_on_target_against,
    _opponent_clean_sheets,
    _opponent_pens_att,
    _opponent_pens_made,
    _opponent_pens_allowed,
    _opponent_pens_att_gk,
    _opponent_pens_missed_gk,
    _opponent_pens_saved,
    _opponent_pens_conceded,
    _opponent_pens_won,
    _opponent_save_pct,
    _opponent_saves,
    _opponent_cards_red,
    _opponent_cards_yellow,
    _opponent_cards_yellow_red,
    _opponent_crosses,
    _opponent_fouled,
    _opponent_fouls,
    _opponent_interceptions,
    _opponent_tackles_won,
    _opponent_offsides,
    _opponent_own_goals,
    _npxg,
    _npxg_per_shot,
    _shots_free_kicks,
    _xg_net,
    _avg_distance_def_actions_gk,
    _crosses_gk,
    _crosses_stopped_gk,
    _crosses_stopped_pct_gk,
    _def_actions_outside_pen_area_gk,
    _goal_kick_length_avg,
    _goal_kicks,
    _passes_completed_launched_gk,
    _passes_gk,
    _passes_launched_gk,
    _passes_length_avg_gk,
    _passes_pct_launched_gk,
    _passes_throws_gk,
    _pct_goal_kicks_launched,
    _pct_passes_launched_gk,
    _psxg_gk,
    _psxg_net_gk,
    _assisted_shots,
    _crosses_into_penalty_area,
    _passes,
    _passes_completed,
    _passes_completed_long,
    _passes_completed_medium,
    _passes_completed_short,
    _passes_into_final_third,
    _passes_into_penalty_area,
    _passes_long,
    _passes_medium,
    _passes_pct,
    _passes_pct_long,
    _passes_pct_medium,
    _passes_pct_short,
    _passes_progressive_distance,
    _passes_short,
    _passes_total_distance,
    _progressive_passes,
    _xa,
    _corner_kicks,
    _corner_kicks_in,
    _corner_kicks_out,
    _corner_kicks_straight,
    _passes_blocked,
    _passes_dead,
    _passes_free_kicks,
    _passes_ground,
    _passes_head,
    _passes_high,
    _passes_intercepted,
    _passes_left_foot,
    _passes_live,
    _passes_low,
    _passes_offsides,
    _passes_oob,
    _passes_other_body,
    _passes_pressure,
    _passes_right_foot,
    _passes_switches,
    _through_balls,
    _throw_ins,
    _gca,
    _gca_defense,
    _gca_dribbles,
    _gca_fouled,
    _gca_passes_dead,
    _gca_passes_live,
    _gca_shots,
    _sca,
    _sca_defense,
    _sca_dribbles,
    _sca_fouled,
    _sca_passes_dead,
    _sca_passes_live,
    _sca_shots,
    _blocked_passes,
    _blocked_shots,
    _blocked_shots_saves,
    _blocks,
    _clearances,
    _dribble_tackles,
    _dribble_tackles_pct,
    _dribbled_past,
    _dribbles_vs,
    _errors,
    _pressure_regain_pct,
    _pressure_regains,
    _pressures,
    _pressures_att_3rd,
    _pressures_def_3rd,
    _pressures_mid_3rd,
    _tackles,
    _tackles_att_3rd,
    _tackles_def_3rd,
    _tackles_interceptions,
    _tackles_mid_3rd,
    _carries,
    _carries_into_final_third,
    _carries_into_penalty_area,
    _carry_distance,
    _carry_progressive_distance,
    _dispossessed,
    _dribbles,
    _dribbles_completed,
    _dribbles_completed_pct,
    _miscontrols,
    _nutmegs,
    _pass_targets,
    _passes_received,
    _passes_received_pct,
    _players_dribbled_past,
    _progressive_carries,
    _progressive_passes_received,
    _touches,
    _touches_att_3rd,
    _touches_att_pen_area,
    _touches_def_3rd,
    _touches_def_pen_area,
    _touches_live_ball,
    _touches_mid_3rd,
    _opponent_possession,
    _xg_against,
    _xg_for
  )
  on conflict(squad_id, id_squad_round)
  do update 
  set 
    attendance = EXCLUDED.attendance,
    goals_against = EXCLUDED.goals_against,
    goals_for = EXCLUDED.goals_for,
    goals_per_shot = EXCLUDED.goals_per_shot,
    goals_per_shot_on_target = EXCLUDED.goals_per_shot_on_target,
    possession = EXCLUDED.possession,
    average_shot_distance = EXCLUDED.average_shot_distance,
    shots_on_target = EXCLUDED.shots_on_target,
    shots_on_target_pct = EXCLUDED.shots_on_target_pct,
    pens_allowed = EXCLUDED.pens_allowed,
    pens_att_gk = EXCLUDED.pens_att_gk,
    pens_missed_gk = EXCLUDED.pens_missed_gk,
    pens_saved = EXCLUDED.pens_saved,
    pens_att = EXCLUDED.pens_att,
    pens_made = EXCLUDED.pens_made,
    pens_conceded = EXCLUDED.pens_conceded,
    pens_won = EXCLUDED.pens_won,
    shots_total = EXCLUDED.shots_total,
    clean_sheets = EXCLUDED.clean_sheets,
    save_pct = EXCLUDED.save_pct,
    saves = EXCLUDED.saves,
    shots_on_target_against = EXCLUDED.shots_on_target_against,
    cards_red = EXCLUDED.cards_red,
    cards_yellow = EXCLUDED.cards_yellow,
    cards_yellow_red = EXCLUDED.cards_yellow_red,
    crosses = EXCLUDED.crosses,
    fouled = EXCLUDED.fouled,
    fouls = EXCLUDED.fouls,
    interceptions = EXCLUDED.interceptions,
    offsides = EXCLUDED.offsides,
    own_goals = EXCLUDED.own_goals,
    tackles_won = EXCLUDED.tackles_won,
    opponent_goals_per_shot = EXCLUDED.opponent_goals_per_shot,
    opponent_goals_per_shot_on_target = EXCLUDED.opponent_goals_per_shot_on_target,
    opponent_shots_on_target = EXCLUDED.opponent_shots_on_target,
    opponent_shots_on_target_pct = EXCLUDED.opponent_shots_on_target_pct,
    opponent_shots_total = EXCLUDED.opponent_shots_total,
    opponent_shots_on_target_against = EXCLUDED.opponent_shots_on_target_against,
    opponent_clean_sheets = EXCLUDED.opponent_clean_sheets,
    opponent_pens_att = EXCLUDED.opponent_pens_att,
    opponent_pens_made = EXCLUDED.opponent_pens_made,
    opponent_pens_allowed = EXCLUDED.opponent_pens_allowed,
    opponent_pens_att_gk = EXCLUDED.opponent_pens_att_gk,
    opponent_pens_missed_gk = EXCLUDED.opponent_pens_missed_gk,
    opponent_pens_saved = EXCLUDED.opponent_pens_saved,
    opponent_pens_conceded = EXCLUDED.opponent_pens_conceded,
    opponent_pens_won = EXCLUDED.opponent_pens_won,
    opponent_save_pct = EXCLUDED.opponent_save_pct,
    opponent_saves = EXCLUDED.opponent_saves,
    opponent_cards_red = EXCLUDED.opponent_cards_red,
    opponent_cards_yellow = EXCLUDED.opponent_cards_yellow,
    opponent_cards_yellow_red = EXCLUDED.opponent_cards_yellow_red,
    opponent_crosses = EXCLUDED.opponent_crosses,
    opponent_fouled = EXCLUDED.opponent_fouled,
    opponent_fouls = EXCLUDED.opponent_fouls,
    opponent_interceptions = EXCLUDED.opponent_interceptions,
    opponent_tackles_won = EXCLUDED.opponent_tackles_won,
    opponent_offsides = EXCLUDED.opponent_offsides,
    opponent_own_goals = EXCLUDED.opponent_own_goals,
    npxg = EXCLUDED.npxg,
    npxg_per_shot = EXCLUDED.npxg_per_shot,
    shots_free_kicks = EXCLUDED.shots_free_kicks,
    xg_net = EXCLUDED.xg_net,
    avg_distance_def_actions_gk = EXCLUDED.avg_distance_def_actions_gk,
    crosses_gk = EXCLUDED.crosses_gk,
    crosses_stopped_gk = EXCLUDED.crosses_stopped_gk,
    crosses_stopped_pct_gk = EXCLUDED.crosses_stopped_pct_gk,
    def_actions_outside_pen_area_gk = EXCLUDED.def_actions_outside_pen_area_gk,
    goal_kick_length_avg = EXCLUDED.goal_kick_length_avg,
    goal_kicks = EXCLUDED.goal_kicks,
    passes_completed_launched_gk = EXCLUDED.passes_completed_launched_gk,
    passes_gk = EXCLUDED.passes_gk,
    passes_launched_gk = EXCLUDED.passes_launched_gk,
    passes_length_avg_gk = EXCLUDED.passes_length_avg_gk,
    passes_pct_launched_gk = EXCLUDED.passes_pct_launched_gk,
    passes_throws_gk = EXCLUDED.passes_throws_gk,
    pct_goal_kicks_launched = EXCLUDED.pct_goal_kicks_launched,
    pct_passes_launched_gk = EXCLUDED.pct_passes_launched_gk,
    psxg_gk = EXCLUDED.psxg_gk,
    psxg_net_gk = EXCLUDED.psxg_net_gk,
    assisted_shots = EXCLUDED.assisted_shots,
    crosses_into_penalty_area = EXCLUDED.crosses_into_penalty_area,
    passes = EXCLUDED.passes,
    passes_completed = EXCLUDED.passes_completed,
    passes_completed_long = EXCLUDED.passes_completed_long,
    passes_completed_medium = EXCLUDED.passes_completed_medium,
    passes_completed_short = EXCLUDED.passes_completed_short,
    passes_into_final_third = EXCLUDED.passes_into_final_third,
    passes_into_penalty_area = EXCLUDED.passes_into_penalty_area,
    passes_long = EXCLUDED.passes_long,
    passes_medium = EXCLUDED.passes_medium,
    passes_pct = EXCLUDED.passes_pct,
    passes_pct_long = EXCLUDED.passes_pct_long,
    passes_pct_medium = EXCLUDED.passes_pct_medium,
    passes_pct_short = EXCLUDED.passes_pct_short,
    passes_progressive_distance = EXCLUDED.passes_progressive_distance,
    passes_short = EXCLUDED.passes_short,
    passes_total_distance = EXCLUDED.passes_total_distance,
    progressive_passes = EXCLUDED.progressive_passes,
    xa = EXCLUDED.xa,
    corner_kicks = EXCLUDED.corner_kicks,
    corner_kicks_in = EXCLUDED.corner_kicks_in,
    corner_kicks_out = EXCLUDED.corner_kicks_out,
    corner_kicks_straight = EXCLUDED.corner_kicks_straight,
    passes_blocked = EXCLUDED.passes_blocked,
    passes_dead = EXCLUDED.passes_dead,
    passes_free_kicks = EXCLUDED.passes_free_kicks,
    passes_ground = EXCLUDED.passes_ground,
    passes_head = EXCLUDED.passes_head,
    passes_high = EXCLUDED.passes_high,
    passes_intercepted = EXCLUDED.passes_intercepted,
    passes_left_foot = EXCLUDED.passes_left_foot,
    passes_live = EXCLUDED.passes_live,
    passes_low = EXCLUDED.passes_low,
    passes_offsides = EXCLUDED.passes_offsides,
    passes_oob = EXCLUDED.passes_oob,
    passes_other_body = EXCLUDED.passes_other_body,
    passes_pressure = EXCLUDED.passes_pressure,
    passes_right_foot = EXCLUDED.passes_right_foot,
    passes_switches = EXCLUDED.passes_switches,
    through_balls = EXCLUDED.through_balls,
    throw_ins = EXCLUDED.throw_ins,
    gca = EXCLUDED.gca,
    gca_defense = EXCLUDED.gca_defense,
    gca_dribbles = EXCLUDED.gca_dribbles,
    gca_fouled = EXCLUDED.gca_fouled,
    gca_passes_dead = EXCLUDED.gca_passes_dead,
    gca_passes_live = EXCLUDED.gca_passes_live,
    gca_shots = EXCLUDED.gca_shots,
    sca = EXCLUDED.sca,
    sca_defense = EXCLUDED.sca_defense,
    sca_dribbles = EXCLUDED.sca_dribbles,
    sca_fouled = EXCLUDED.sca_fouled,
    sca_passes_dead = EXCLUDED.sca_passes_dead,
    sca_passes_live = EXCLUDED.sca_passes_live,
    sca_shots = EXCLUDED.sca_shots,
    blocked_passes = EXCLUDED.blocked_passes,
    blocked_shots = EXCLUDED.blocked_shots,
    blocked_shots_saves = EXCLUDED.blocked_shots_saves,
    blocks = EXCLUDED.blocks,
    clearances = EXCLUDED.clearances,
    dribble_tackles = EXCLUDED.dribble_tackles,
    dribble_tackles_pct = EXCLUDED.dribble_tackles_pct,
    dribbled_past = EXCLUDED.dribbled_past,
    dribbles_vs = EXCLUDED.dribbles_vs,
    errors = EXCLUDED.errors,
    pressure_regain_pct = EXCLUDED.pressure_regain_pct,
    pressure_regains = EXCLUDED.pressure_regains,
    pressures = EXCLUDED.pressures,
    pressures_att_3rd = EXCLUDED.pressures_att_3rd,
    pressures_def_3rd = EXCLUDED.pressures_def_3rd,
    pressures_mid_3rd = EXCLUDED.pressures_mid_3rd,
    tackles = EXCLUDED.tackles,
    tackles_att_3rd = EXCLUDED.tackles_att_3rd,
    tackles_def_3rd = EXCLUDED.tackles_def_3rd,
    tackles_interceptions = EXCLUDED.tackles_interceptions,
    tackles_mid_3rd = EXCLUDED.tackles_mid_3rd,
    carries = EXCLUDED.carries,
    carries_into_final_third = EXCLUDED.carries_into_final_third,
    carries_into_penalty_area = EXCLUDED.carries_into_penalty_area,
    carry_distance = EXCLUDED.carry_distance,
    carry_progressive_distance = EXCLUDED.carry_progressive_distance,
    dispossessed = EXCLUDED.dispossessed,
    dribbles = EXCLUDED.dribbles,
    dribbles_completed = EXCLUDED.dribbles_completed,
    dribbles_completed_pct = EXCLUDED.dribbles_completed_pct,
    miscontrols = EXCLUDED.miscontrols,
    nutmegs = EXCLUDED.nutmegs,
    pass_targets = EXCLUDED.pass_targets,
    passes_received = EXCLUDED.passes_received,
    passes_received_pct = EXCLUDED.passes_received_pct,
    players_dribbled_past = EXCLUDED.players_dribbled_past,
    progressive_carries = EXCLUDED.progressive_carries,
    progressive_passes_received = EXCLUDED.progressive_passes_received,
    touches = EXCLUDED.touches,
    touches_att_3rd = EXCLUDED.touches_att_3rd,
    touches_att_pen_area = EXCLUDED.touches_att_pen_area,
    touches_def_3rd = EXCLUDED.touches_def_3rd,
    touches_def_pen_area = EXCLUDED.touches_def_pen_area,
    touches_live_ball = EXCLUDED.touches_live_ball,
    touches_mid_3rd = EXCLUDED.touches_mid_3rd,
    opponent_possession = EXCLUDED.opponent_possession,
    xg_against = EXCLUDED.xg_against,
    xg_for = EXCLUDED.xg_for
  where squad_id = _squad_id
    and id_squad_round = _id_squad_round;

end $$;