drop view if exists vw_player_train_data;
drop view if exists vw_keeper_train_data;
drop view if exists vw_player_performance;
drop view if exists vw_keeper_performance;
drop view if exists vw_squad_performance;
drop table if exists tb_player_performance;
drop table if exists tb_keeper_performance;
drop table if exists tb_squad_performance;
drop table if exists tb_player_match_stats;
drop table if exists tb_squad_match_stats;
drop table if exists tb_squad_round;
drop table if exists tb_player;
drop table if exists tb_squad;

create table tb_country(
	country varchar(50),
	alpha varchar(3)
);

create table tb_competition(
  competition_id serial,
  competition varchar(50),
  unique (competition)
)

create table tb_squad(
	squad_id varchar(20),
	squad_name varchar(50),
	country char(2),
	primary key(squad_id)
);

create table tb_squad_round(
  id_squad_round serial,
  competition_id integer,
  round varchar(60),
  round_date date,
  dayofweek varchar(3),
  venue varchar(8),
  squad_id varchar(50),
  opponent varchar(50),
  referee varchar(70),
  result  char(1),
  captain varchar(50),
  formation varchar(15),
  primary key (id_squad_round),
  unique(squad_id, competition_id,round_date)
);

create table tb_player(
	player_id varchar(20),
	squad_id  varchar(20),
	player_name varchar(50),
	born date,
	nationality varchar(10),
	field_area varchar(5),
	position varchar(20),
	foot varchar(6),
	height smallint,
	weight smallint,
	primary key(player_id)
);


create table tb_squad_match_stats(
	id_squad_match_stat serial,
  id_squad_round integer,
  squad_id varchar(50),
  attendance numeric(7,1),
  goals_against numeric(3,1),
  goals_for numeric(3,1),
  goals_per_shot numeric(3,2),
  goals_per_shot_on_target numeric(3,2),
  possession numeric(7,1),
  average_shot_distance numeric(7,1),
  shots_on_target numeric(3,1),
  shots_on_target_pct numeric(7,1),
  pens_allowed numeric(3,1),
  pens_att_gk numeric(3,1),
  pens_missed_gk numeric(3,1),
  pens_saved numeric(3,1),
  pens_att numeric(3,1),
  pens_made numeric(3,1),
  pens_conceded numeric(3,1),
  pens_won numeric(3,1),
  shots_total numeric(3,1),
  clean_sheets numeric(3,1),
  save_pct numeric(7,1),
  saves numeric(3,1),
  shots_on_target_against numeric(3,1),
  cards_red numeric(3,1),
  cards_yellow numeric(3,1),
  cards_yellow_red numeric(3,1),
  crosses numeric(3,1),
  fouled numeric(3,1),
  fouls numeric(3,1),
  interceptions numeric(3,1),
  offsides numeric(3,1),
  own_goals numeric(3,1),
  tackles_won numeric(3,1),
  opponent_goals_per_shot numeric(3,2),
  opponent_goals_per_shot_on_target numeric(3,2),
  opponent_shots_on_target numeric(3,1),
  opponent_shots_on_target_pct numeric(7,1),
  opponent_shots_total numeric(3,1),
  opponent_shots_on_target_against numeric(3,1),
  opponent_clean_sheets numeric(3,1),
  opponent_pens_att numeric(3,1),
  opponent_pens_made numeric(3,1),
  opponent_pens_allowed numeric(3,1),
  opponent_pens_att_gk numeric(3,1),
  opponent_pens_missed_gk numeric(3,1),
  opponent_pens_saved numeric(3,1),
  opponent_pens_conceded numeric(3,1),
  opponent_pens_won numeric(3,1),
  opponent_save_pct numeric(7,1),
  opponent_saves numeric(3,1),
  opponent_cards_red numeric(3,1),
  opponent_cards_yellow numeric(3,1),
  opponent_cards_yellow_red numeric(3,1),
  opponent_crosses numeric(3,1),
  opponent_fouled numeric(3,1),
  opponent_fouls numeric(3,1),
  opponent_interceptions numeric(3,1),
  opponent_tackles_won numeric(3,1),
  opponent_offsides numeric(3,1),
  opponent_own_goals numeric(3,1),
  npxg numeric(7,1),
  npxg_per_shot numeric(7,1),
  shots_free_kicks numeric(7,1),
  xg_net numeric(7,1),
  avg_distance_def_actions_gk numeric(7,1),
  crosses_gk numeric(7,1),
  crosses_stopped_gk numeric(7,1),
  crosses_stopped_pct_gk numeric(7,1),
  def_actions_outside_pen_area_gk numeric(7,1),
  goal_kick_length_avg numeric(7,1),
  goal_kicks numeric(7,1),
  passes_completed_launched_gk numeric(7,1),
  passes_gk numeric(7,1),
  passes_launched_gk numeric(7,1),
  passes_length_avg_gk numeric(7,1),
  passes_pct_launched_gk numeric(7,1),
  passes_throws_gk numeric(7,1),
  pct_goal_kicks_launched numeric(7,1),
  pct_passes_launched_gk numeric(7,1),
  psxg_gk numeric(7,1),
  psxg_net_gk numeric(7,1),
  assisted_shots numeric(7,1),
  crosses_into_penalty_area numeric(7,1),
  passes numeric(7,1),
  passes_completed numeric(7,1),
  passes_completed_long numeric(7,1),
  passes_completed_medium numeric(7,1),
  passes_completed_short numeric(7,1),
  passes_into_final_third numeric(7,1),
  passes_into_penalty_area numeric(7,1),
  passes_long numeric(7,1),
  passes_medium numeric(7,1),
  passes_pct numeric(7,1),
  passes_pct_long numeric(7,1),
  passes_pct_medium numeric(7,1),
  passes_pct_short numeric(7,1),
  passes_progressive_distance numeric(7,1),
  passes_short numeric(7,1),
  passes_total_distance numeric(7,1),
  progressive_passes numeric(7,1),
  xa numeric(7,1),
  corner_kicks numeric(7,1),
  corner_kicks_in numeric(7,1),
  corner_kicks_out numeric(7,1),
  corner_kicks_straight numeric(7,1),
  passes_blocked numeric(7,1),
  passes_dead numeric(7,1),
  passes_free_kicks numeric(7,1),
  passes_ground numeric(7,1),
  passes_head numeric(7,1),
  passes_high numeric(7,1),
  passes_intercepted numeric(7,1),
  passes_left_foot numeric(7,1),
  passes_live numeric(7,1),
  passes_low numeric(7,1),
  passes_offsides numeric(7,1),
  passes_oob numeric(7,1),
  passes_other_body numeric(7,1),
  passes_pressure numeric(7,1),
  passes_right_foot numeric(7,1),
  passes_switches numeric(7,1),
  through_balls numeric(7,1),
  throw_ins numeric(7,1),
  gca numeric(7,1),
  gca_defense numeric(7,1),
  gca_dribbles numeric(7,1),
  gca_fouled numeric(7,1),
  gca_passes_dead numeric(7,1),
  gca_passes_live numeric(7,1),
  gca_shots numeric(7,1),
  sca numeric(7,1),
  sca_defense numeric(7,1),
  sca_dribbles numeric(7,1),
  sca_fouled numeric(7,1),
  sca_passes_dead numeric(7,1),
  sca_passes_live numeric(7,1),
  sca_shots numeric(7,1),
  blocked_passes numeric(7,1),
  blocked_shots numeric(7,1),
  blocked_shots_saves numeric(7,1),
  blocks numeric(7,1),
  clearances numeric(7,1),
  dribble_tackles numeric(7,1),
  dribble_tackles_pct numeric(7,1),
  dribbled_past numeric(7,1),
  dribbles_vs numeric(7,1),
  errors numeric(7,1),
  pressure_regain_pct numeric(7,1),
  pressure_regains numeric(7,1),
  pressures numeric(7,1),
  pressures_att_3rd numeric(7,1),
  pressures_def_3rd numeric(7,1),
  pressures_mid_3rd numeric(7,1),
  tackles numeric(7,1),
  tackles_att_3rd numeric(7,1),
  tackles_def_3rd numeric(7,1),
  tackles_interceptions numeric(7,1),
  tackles_mid_3rd numeric(7,1),
  carries numeric(7,1),
  carries_into_final_third numeric(7,1),
  carries_into_penalty_area numeric(7,1),
  carry_distance numeric(7,1),
  carry_progressive_distance numeric(7,1),
  dispossessed numeric(7,1),
  dribbles numeric(7,1),
  dribbles_completed numeric(7,1),
  dribbles_completed_pct numeric(7,1),
  miscontrols numeric(7,1),
  nutmegs numeric(7,1),
  pass_targets numeric(7,1),
  passes_received numeric(7,1),
  passes_received_pct numeric(7,1),
  players_dribbled_past numeric(7,1),
  progressive_carries numeric(7,1),
  progressive_passes_received numeric(7,1),
  touches numeric(7,1),
  touches_att_3rd numeric(7,1),
  touches_att_pen_area numeric(7,1),
  touches_def_3rd numeric(7,1),
  touches_def_pen_area numeric(7,1),
  touches_live_ball numeric(7,1),
  touches_mid_3rd numeric(7,1),
  opponent_possession numeric(7,1),
  xg_against numeric(7,1),
  xg_for numeric(7,1)
);

create table if not exists tb_player_match_stats (
  player_id varchar(20),
  id_squad_round integer,
  clean_sheets numeric(4,1),
  game_started varchar(2),
  goals_against_gk numeric(4,1),
  minutes varchar(6),
  pens_allowed numeric(4,1),
  pens_att_gk numeric(4,1),
  pens_missed_gk numeric(4,1),
  pens_saved numeric(4,1),
  position varchar(10),
  save_pct numeric(3,2),
  saves numeric(4,1),
  shots_on_target_against numeric(4,1),
  assists numeric(4,1),
  assists_per90 numeric(3,2),
  cards_red numeric(4,1),
  cards_yellow numeric(4,1),
  crosses numeric(4,1),
  fouled numeric(4,1),
  fouls numeric(4,1),
  games numeric(4,1),
  games_starts numeric(4,1),
  goals numeric(4,1),
  goals_assists_pens_per90 numeric(3,2),
  goals_assists_per90 numeric(3,2),
  goals_pens_per90 numeric(3,2),
  goals_per90 numeric(3,2),
  interceptions numeric(4,1),
  offsides numeric(4,1),
  own_goals numeric(4,1),
  pens_att numeric(4,1),
  pens_conceded numeric(4,1),
  pens_made numeric(4,1),
  pens_won numeric(4,1),
  shots_on_target numeric(4,1),
  shots_total numeric(4,1),
  tackles_won numeric(4,1),
  bench_explain varchar(70)
);

create table tb_player_performance(
	player_id varchar(20),
	squad_id varchar(20),
	player_name varchar(50),
	field_area varchar(20),
	position varchar(20),
	round_num smallint,
  venue char(4),
	date date,
	opponent varchar(50),
	score numeric(3,1),
	goals numeric(4,1),
  clean_sheets numeric(4,1),
	assists numeric(4,1),
	tackles_won numeric(4,1),
	shots_total numeric(4,1),
	shots_on_target numeric(4,1),
	fouled numeric(4,1),
	own_goals numeric(4,1),
	cards_red numeric(4,1),
	cards_yellow numeric(4,1),
	fouls numeric(4,1),
	offsides numeric(4,1),
	pens_made numeric(4,1)
);

create table tb_keeper_performance(
	player_id varchar(20),
	squad_id varchar(20),
	player_name varchar(50),
	field_area varchar(20),
	position varchar(20),
	round_num smallint,
  venue char(4),
	date date,
	opponent varchar(50),
	score numeric(3,1),
	clean_sheets numeric(3,2),
	goals numeric(3,2),
	assists numeric(3,2),
	cards_red numeric(3,2),
	cards_yellow numeric(3,2),
	tackles_won numeric(3,2),
	shots_total numeric(3,2),
	shots_on_target numeric(3,2),
	fouls numeric(4,1),
	pens_made numeric(3,2),
  pens_saved numeric(3,2),
  goals_against_gk numeric(3,2),
  saves numeric(4,1)
);

create table tb_squad_performance(
	squad_id varchar(20),
  squad_name varchar(50),
  formation varchar(15),
	captain varchar(50),
	round_num smallint,
  venue char(4),
	date date,
	opponent varchar(50),
	clean_sheets numeric(4,1),
	possession numeric(4,1),
	goals numeric(4,1),
	goals_per_shot numeric(4,1),
	tackles_won numeric(4,1),
	fouled numeric(4,1),
	shots_total numeric(4,1),
	shots_on_target numeric(4,1),
	cards_red numeric(4,1),
	cards_yellow numeric(4,1),
	fouls numeric(4,1),
	pens_conceded numeric(4,1),
	pens_won numeric(4,1),
	goals_against numeric(4,1),
	saves numeric(4,1),
	opponent_goals_per_shot numeric(4,1),
	opponent_shots_on_target numeric(4,1),
	opponent_shots_total numeric(4,1)
);

alter table tb_player
	add constraint fk_tb_squad_TO_tb_player
	foreign key (squad_id)
	references tb_squad(squad_id);

alter table tb_squad_match_stats
	add constraint fk_tb_squad_TO_tb_squad_match_stats
	foreign key (squad_id)
	references tb_squad(squad_id);

alter table tb_squad_match_stats
	add constraint fk_tb_squad_round_TO_tb_squad_match_stats
	foreign key (id_squad_round)
	references tb_squad_round(id_squad_round);

alter table tb_player_match_stats
	add constraint fk_tb_squad_TO_tb_player_match_stats
	foreign key (player_id)
	references tb_player(player_id);

alter table tb_player_match_stats
	add constraint fk_tb_squad_round_TO_tb_player_match_stats
	foreign key (id_squad_round)
	references tb_squad_round(id_squad_round);